services:
  liaison-service:
    build: ./liaison-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  deadlines-service:
    build: ./deadlines-service
    ports:
      - 3002:3002
    environment:
      - PORT=3002

  email-service:
    build: ./email-service
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=topamatching.noreply@gmail.com
      - SMTP_PASS=jzsd rxwm txve wjdr
      - DEFAULT_FROM_EMAIL=topamatching.noreply@gmail.com
      - DEFAULT_REPLY_TO=jkaros@umass.edu
    restart: always
