services:
  deadlines-service:
    build: ./deadlines-service
    ports:
      - 3002:3002
    environment:
      - PORT=3002

  email-service:
    build: ./email-service
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=${GMAIL_DUMMY}
      - SMTP_PASS=${PASS}
      - DEFAULT_FROM_EMAIL=${GMAIL_DUMMY}
      - DEFAULT_REPLY_TO=${REPLY}
    restart: always

  association-0:
    build: ./association-service
    environment:
      - PORT=4000
      - CONTAINER_ID_ID=0
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  association-1:
    build: ./association-service
    environment:
      - PORT=4000
      - CONTAINER_ID=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  caddy:
    image: caddy:2
    ports:
      - "8080:8080"
      - "3999:3999"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - association-0
      - association-1
      - liaison-1
      - liaison-2
      - liaison-3

  liaison-1:
    build: ./liaison-service
    environment:
      - PORT=3001
      - EMAIL_SERVICE_URL=http://email-service:3000/contact_assignee_candidate
      - SIMULATED_LATENCY=1500
      - REPLICA_ID=replica-1
  liaison-2:
    build: ./liaison-service
    environment:
      - PORT=3001
      - EMAIL_SERVICE_URL=http://email-service:3000/contact_assignee_candidate
      - SIMULATED_LATENCY=1500
      - REPLICA_ID=replica-2
  liaison-3:
    build: ./liaison-service
    environment:
      - PORT=3001
      - EMAIL_SERVICE_URL=http://email-service:3000/contact_assignee_candidate
      - SIMULATED_LATENCY=1500
      - REPLICA_ID=replica-3

  redis:
    image: redis:7
    ports:
      - "6379:6379"