services:

  deadlines-service:
    build: ./deadlines-service
    ports:
      - 3002:3002
    environment:
      - PORT=3002

  email-service:
    build: ./email-service
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=${GMAIL_DUMMY}
      - SMTP_PASS=${PASS}
      - DEFAULT_FROM_EMAIL=${GMAIL_DUMMY}
      - DEFAULT_REPLY_TO=${REPLY}
    restart: always

  caddy:
    image: caddy:2
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - liaison-service
    
  liaison-service:
    build: ./liaison-service
    environment:
      - PORT=3001
      - EMAIL_SERVICE_URL=http://email-service:3000/contact_assignee_candidate
      - SIMULATED_LATENCY=1500
    deploy:
      replicas: 3